version: "3.8"
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nginx_equeue
        image: nginx_equeue
        environment:
            - VITE_API_URL=${VITE_API_URL:-https://elreg.rada-uzhgorod.gov.ua}
            - VITE_API_HOST=${VITE_API_HOST:-elreg.rada-uzhgorod.gov.ua}
            - .env
        ports:
            - "8080:80"
        volumes:
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
